service: popin-backend
frameworkVersion: '3'

provider:
  region: eu-north-1
  name: aws
  runtime: python3.8
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ecr:InitiateLayerUpload"
            - "ecr:SetRepositoryPolicy"
            - "ecr:GetRepositoryPolicy"
          Resource: [ "arn:aws:ecr:eu-north-1:925874818011:repository/*" ]
functions:
  popin:
    image: 925874818011.dkr.ecr.eu-north-1.amazonaws.com/popin:latest
    events:
      - httpApi:
          path: /
          method: post

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    cacheLocation: ./.serverless/.requirements_cache

package:
  excludeDevDependencies: true
  patterns:
    - "!venv/**"
    - "!node_modules/**"

