service: popin-backend
frameworkVersion: "3"

provider:
  region: eu-north-1
  name: aws
  runtime: python3.8
  ecr:
    images:
      appimage:
        path: ./
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:*"
          Resource:
            - "arn:aws:s3:::popin-data-bucket/*"

functions:
  popin:
    timeout: 60
    image:
      name: appimage
    events:
      - http:
          path: /
          method: post
          cors: true

package:
  excludeDevDependencies: true
  patterns:
    - "!venv/**"
    - "!node_modules/**"
